[package]
name = "lexer"
version = "0.1.0"
authors = ["Steve Akinyemi <appcypher@outlook.com>"]
license = "Apache-2.0 WITH LLVM-exception"
edition = "2018"

[features]
debug = []

[lib]
name = "lexer"
path = "lexer.rs"
